"""initial

Revision ID: 802e0f57c700
Revises: 
Create Date: 2026-02-23 04:21:09.113536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '802e0f57c700'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_ja', sa.String(length=255), nullable=True),
    sa.Column('designer', sa.String(length=255), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('headquarters', sa.String(length=255), nullable=True),
    sa.Column('website_jp', sa.String(length=512), nullable=True),
    sa.Column('website_us', sa.String(length=512), nullable=True),
    sa.Column('has_redirect', sa.Boolean(), nullable=False),
    sa.Column('style_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('price_range', sa.String(length=50), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_ja', sa.Text(), nullable=True),
    sa.Column('shipping_tier', sa.String(length=50), nullable=True),
    sa.Column('buy_guide', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('local_path', sa.String(length=1024), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proxy_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('fee_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supported_retailers', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('shipping_methods', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('avg_delivery_days_us', sa.Integer(), nullable=True),
    sa.Column('pros', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('cons', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxy_services_slug'), 'proxy_services', ['slug'], unique=True)
    op.create_table('retailers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('ships_to_us', sa.Boolean(), nullable=False),
    sa.Column('shipping_tier', sa.String(length=50), nullable=True),
    sa.Column('supported_proxies', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('payment_methods', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retailers_slug'), 'retailers', ['slug'], unique=True)
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('theme', sa.String(length=255), nullable=True),
    sa.Column('lookbook_url', sa.String(length=512), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_ja', sa.String(length=255), nullable=True),
    sa.Column('item_type', sa.String(length=100), nullable=True),
    sa.Column('price_jpy', sa.Integer(), nullable=True),
    sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('material', sa.String(length=255), nullable=True),
    sa.Column('sizes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('primary_image_url', sa.String(length=1024), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('retailer_id', sa.Integer(), nullable=False),
    sa.Column('price_jpy', sa.Integer(), nullable=True),
    sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('available_sizes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_listings')
    op.drop_table('items')
    op.drop_table('collections')
    op.drop_index(op.f('ix_retailers_slug'), table_name='retailers')
    op.drop_table('retailers')
    op.drop_index(op.f('ix_proxy_services_slug'), table_name='proxy_services')
    op.drop_table('proxy_services')
    op.drop_table('media')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
